//! The state of the browser and everything that changes it. `App` can be driven without a
//! terminal, which is how it is tested. It does not draw.

use super::Launch;
use crate::launch::{NewSession, default_args};
use crate::paths::{self, Candidate};
use crate::preset::Preset;
use crate::query::{self, Searcher};
use crate::store::{self, Session};
use crate::{tags, tickets, transcript};
use ratatui::{crossterm::event::KeyCode, widgets::ListState};
use std::collections::HashSet;
use std::path::PathBuf;
use std::process::Command;

#[derive(Clone, Copy, PartialEq)]
pub(super) enum Field {
    Title,
    Tags,
    Tickets,
    Note,
    Flags,
}

impl Field {
    pub(super) fn label(self) -> &'static str {
        match self {
            Field::Title => "Title",
            Field::Tags => "Tags (space-separated)",
            Field::Tickets => "Tickets (space or comma separated)",
            Field::Note => "Note",
            Field::Flags => "claude flags",
        }
    }
}

pub(super) enum Mode {
    Browse,
    Edit(Field, String),
    ConfirmDelete,
    /// Wrapped conversation text and the first visible line.
    Preview(Vec<String>, usize),
    /// Every tag with its number of sessions, and the selected row.
    Tags(Vec<(String, usize)>, ListState),
    /// The dialog that starts a new session.
    New(NewForm),
}

/// The fields of the new session dialog, in the order the cursor visits them.
#[derive(Clone, Copy, PartialEq, Debug)]
pub(super) enum NewField {
    Dir,
    Prompt,
    Tickets,
    Title,
}

impl NewField {
    pub(super) const ALL: [NewField; 4] = [
        NewField::Dir,
        NewField::Prompt,
        NewField::Tickets,
        NewField::Title,
    ];

    pub(super) fn label(self) -> &'static str {
        match self {
            NewField::Dir => "Directory",
            NewField::Prompt => "Message",
            NewField::Tickets => "Tickets",
            NewField::Title => "Title",
        }
    }

    fn index(self) -> usize {
        Self::ALL.iter().position(|f| *f == self).unwrap_or(0)
    }
}

/// What has been typed in the new session dialog.
pub(super) struct NewForm {
    pub(super) dir: String,
    pub(super) prompt: String,
    /// Space or comma separated, as in the ticket editor.
    pub(super) tickets: String,
    pub(super) title: String,
    pub(super) focus: NewField,
    /// Directories that could finish `dir`, for the line under the directory field.
    pub(super) suggestions: Vec<Candidate>,
    /// Directories sessions were started in, most recent first.
    used: Vec<String>,
    /// Why the session was not started.
    pub(super) error: Option<String>,
}

impl NewForm {
    pub(super) fn value(&self, field: NewField) -> &str {
        match field {
            NewField::Dir => &self.dir,
            NewField::Prompt => &self.prompt,
            NewField::Tickets => &self.tickets,
            NewField::Title => &self.title,
        }
    }

    fn value_mut(&mut self) -> &mut String {
        match self.focus {
            NewField::Dir => &mut self.dir,
            NewField::Prompt => &mut self.prompt,
            NewField::Tickets => &mut self.tickets,
            NewField::Title => &mut self.title,
        }
    }

    fn refresh_suggestions(&mut self) {
        let home = home();
        self.suggestions = paths::candidates(&self.dir, &self.used, home.as_deref());
    }
}

fn home() -> Option<PathBuf> {
    std::env::var_os("HOME").map(PathBuf::from)
}

/// Where the title shown for a session comes from, in order of preference.
#[derive(Debug, PartialEq)]
pub(super) enum TitleKind {
    /// Set by the user or the agent via `sessions title`.
    Own,
    /// Generated by Claude Code itself.
    Native,
    /// First prompt of the session, cut to size.
    Suggestion,
    Missing,
}

pub(super) fn shown_title(s: &Session) -> (TitleKind, &str) {
    match (&s.title, &s.native_title, &s.suggestion) {
        (Some(t), _, _) => (TitleKind::Own, t),
        (None, Some(t), _) => (TitleKind::Native, t),
        (None, None, Some(t)) => (TitleKind::Suggestion, t),
        _ => (TitleKind::Missing, ""),
    }
}

/// Current branch of `dir`, or `None` outside a repository or on a detached HEAD.
pub(super) fn current_branch(dir: &str) -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .current_dir(dir)
        .output()
        .ok()?;
    let branch = String::from_utf8(out.stdout).ok()?.trim().to_string();
    (out.status.success() && !branch.is_empty() && branch != "HEAD").then_some(branch)
}

pub(super) struct App {
    pub(super) sessions: Vec<Session>,
    /// Ids that still have a transcript, i.e. can actually be resumed.
    pub(super) resumable: HashSet<String>,
    pub(super) launch_dir: String,
    pub(super) query: String,
    pub(super) show_untitled: bool,
    /// Whether archived sessions are listed too.
    pub(super) show_archived: bool,
    pub(super) only_here: bool,
    /// Set while filtering to the branch that is checked out in `launch_dir`.
    pub(super) only_branch: Option<String>,
    pub(super) mode: Mode,
    pub(super) list: ListState,
    /// Rows the list shows at once; set while drawing, used for PageUp/PageDown.
    pub(super) page: usize,
    pub(super) status: String,
}

pub(super) fn in_dir(session_cwd: &str, launch_dir: &str) -> bool {
    let below = |a: &str, b: &str| a == b || a.strip_prefix(b).is_some_and(|r| r.starts_with('/'));
    below(session_cwd, launch_dir) || below(launch_dir, session_cwd)
}

impl App {
    /// Indices into `sessions`, filtered and ordered for display.
    pub(super) fn visible(&self) -> Vec<usize> {
        let search = Searcher::new(&self.query);
        let mut scored: Vec<(i64, usize)> = self
            .sessions
            .iter()
            .enumerate()
            .filter(|(_, s)| self.in_scope(s))
            .filter_map(|(i, s)| search.score(s).map(|score| (score, i)))
            .collect();
        scored.sort_by(|a, b| {
            b.0.cmp(&a.0).then_with(|| {
                self.sessions[b.1]
                    .updated_at
                    .cmp(&self.sessions[a.1].updated_at)
            })
        });
        scored.into_iter().map(|(_, i)| i).collect()
    }

    /// Whether the list may show `s` before the search box is looked at: the toggles for empty and
    /// archived sessions and the directory and branch filters.
    fn in_scope(&self, s: &Session) -> bool {
        (self.show_untitled || shown_title(s).0 != TitleKind::Missing)
            && (self.show_archived || !s.archived)
            && (!self.only_here || in_dir(&s.cwd, &self.launch_dir))
            && self
                .only_branch
                .as_ref()
                .is_none_or(|b| s.branch.as_ref() == Some(b))
    }

    /// Opens the tag view. It counts the sessions the list can show, so a count matches what
    /// selecting the tag leaves in the list.
    pub(super) fn open_tags(&mut self) {
        let counts = tags::counts(self.sessions.iter().filter(|s| self.in_scope(s)));
        let mut state = ListState::default();
        state.select(if counts.is_empty() { None } else { Some(0) });
        self.mode = Mode::Tags(counts, state);
    }

    /// Adds the tag as an exact `#tag` word to the search box, or takes it out if it is there.
    pub(super) fn toggle_tag_filter(&mut self, tag: &str) {
        self.query = query::toggle_tag_word(&self.query, tag);
        self.list.select(Some(0));
        self.clamp();
    }

    /// Existing tags that could finish the word being typed in the tag editor.
    pub(super) fn tag_suggestions(&self, text: &str) -> Vec<String> {
        tags::suggestions(&tags::vocabulary(&self.sessions), text)
    }

    pub(super) fn selected(&self) -> Option<usize> {
        self.visible().get(self.list.selected()?).copied()
    }

    /// Reloads from disk and keeps the cursor on the same session even if the order changed.
    pub(super) fn reload(&mut self) {
        let selected_id = self.selected().map(|i| self.sessions[i].id.clone());
        match store::load() {
            Ok(s) => self.sessions = s,
            Err(e) => self.status = format!("{e:#}"),
        }
        self.resumable = transcript::existing_ids();
        let pos = selected_id.and_then(|id| {
            self.visible()
                .iter()
                .position(|&i| self.sessions[i].id == id)
        });
        if pos.is_some() {
            self.list.select(pos);
        }
        self.clamp();
    }

    pub(super) fn clamp(&mut self) {
        let n = self.visible().len();
        self.list.select(if n == 0 {
            None
        } else {
            Some(self.list.selected().unwrap_or(0).min(n - 1))
        });
    }

    pub(super) fn mv(&mut self, delta: isize) {
        let n = self.visible().len() as isize;
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list.select(Some((cur + delta).rem_euclid(n) as usize));
        }
    }

    /// Moves the cursor without wrapping around, for paging and the mouse wheel.
    pub(super) fn move_by(&mut self, delta: isize) {
        let n = self.visible().len();
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list
                .select(Some((cur + delta).clamp(0, n as isize - 1) as usize));
        }
    }

    pub(super) fn jump_to_end(&mut self) {
        let n = self.visible().len();
        self.list.select(n.checked_sub(1));
    }

    /// Switches the branch filter on (for the branch checked out in the launch directory) or off.
    pub(super) fn toggle_branch_filter(&mut self) {
        if self.only_branch.is_some() {
            self.only_branch = None;
        } else if let Some(branch) = current_branch(&self.launch_dir) {
            self.only_branch = Some(branch);
        } else {
            self.status = "No git branch checked out in this directory".into();
        }
        self.clamp();
    }

    pub(super) fn open_preview(&mut self, width: u16) {
        let Some(i) = self.selected() else { return };
        let Some(path) = transcript::find(&self.sessions[i].id) else {
            self.status = "Transcript is gone, nothing to preview".into();
            return;
        };
        // Leave room for the border and a column of padding.
        match transcript::preview(&path, (width as usize).saturating_sub(4)) {
            Ok(lines) if !lines.is_empty() => self.mode = Mode::Preview(lines, 0),
            Ok(_) => self.status = "Nothing to preview yet".into(),
            Err(e) => self.status = format!("{e:#}"),
        }
    }

    /// Initial text of the edit prompt for the selected session.
    pub(super) fn prefill(&self, field: Field) -> Option<String> {
        let s = &self.sessions[self.selected()?];
        Some(match field {
            Field::Title => shown_title(s).1.to_string(),
            Field::Tags => s.tags.join(" "),
            Field::Tickets => s.tickets.join(" "),
            Field::Note => s.note.clone().unwrap_or_default(),
            Field::Flags => default_args(),
        })
    }

    /// Persists an edit of the selected session. Empty titles are ignored; empty tags/notes clear them.
    pub(super) fn apply_edit(&mut self, field: Field, text: String) {
        let Some(i) = self.selected() else { return };
        if field == Field::Tags {
            let keys = crate::tags::new_ticket_keys(&self.sessions[i].tags, &text);
            if !keys.is_empty() {
                self.status = format!(
                    "{} looks like a ticket key: add it with ^K. Tags are lower case. Not saved",
                    keys.join(" ")
                );
                return;
            }
        }
        let id = self.sessions[i].id.clone();
        let res = store::update(|all| {
            let Some(s) = all.iter_mut().find(|s| s.id == id) else {
                return;
            };
            match field {
                Field::Title if !text.is_empty() => {
                    s.title = Some(text);
                    s.updated_at = chrono::Utc::now();
                }
                Field::Tags => s.tags = crate::tags::reconcile(&s.tags, &text),
                Field::Tickets => {
                    s.tickets = tickets::parse_list(&text);
                }
                Field::Note => s.note = Some(text).filter(|t| !t.is_empty()),
                _ => {}
            }
        });
        if let Err(e) = res {
            self.status = format!("{e:#}");
        }
        self.reload();
    }

    /// Archives the selected session, or brings it back if it is archived already.
    pub(super) fn toggle_archived(&mut self) {
        let Some(i) = self.selected() else { return };
        let (id, archived) = (self.sessions[i].id.clone(), !self.sessions[i].archived);
        let res = store::update(|all| {
            if let Some(s) = all.iter_mut().find(|s| s.id == id) {
                s.archived = archived;
            }
        });
        if let Err(e) = res {
            self.status = format!("{e:#}");
        }
        self.reload();
    }

    pub(super) fn launch(&mut self, i: usize, args: Vec<String>) -> Option<Launch> {
        let session = self.sessions[i].clone();
        if !self.resumable.contains(&session.id) {
            self.status =
                "Transcript is gone, so this session can't be resumed (see `sessions prune`)"
                    .into();
            return None;
        }
        Some(Launch::Resume { session, args })
    }

    /// Opens the new session dialog, with the directory the browser was started in.
    pub(super) fn open_new(&mut self) {
        let mut by_recency: Vec<&Session> = self.sessions.iter().collect();
        by_recency.sort_by_key(|s| std::cmp::Reverse(s.updated_at));
        let mut used: Vec<String> = Vec::new();
        for s in by_recency {
            if !s.cwd.is_empty() && !used.contains(&s.cwd) {
                used.push(s.cwd.clone());
            }
        }
        let dir = if self.launch_dir.is_empty() {
            std::env::current_dir()
                .map(|p| p.display().to_string())
                .unwrap_or_default()
        } else {
            self.launch_dir.clone()
        };
        let mut form = NewForm {
            dir,
            prompt: String::new(),
            tickets: String::new(),
            title: String::new(),
            focus: NewField::Dir,
            suggestions: Vec::new(),
            used,
            error: None,
        };
        form.refresh_suggestions();
        self.mode = Mode::New(form);
    }

    /// Handles a key in the new session dialog. `Tab` completes the directory, the arrows and
    /// `Enter` move between the fields, `Enter` in the last one starts the session, and `Esc`
    /// leaves the list as it was. Returns what to start, if anything.
    pub(super) fn new_key(&mut self, code: KeyCode, ctrl: bool) -> Option<Launch> {
        let Mode::New(form) = &mut self.mode else {
            return None;
        };
        let step = |form: &mut NewForm, delta: isize| {
            let next =
                (form.focus.index() as isize + delta).clamp(0, NewField::ALL.len() as isize - 1);
            form.focus = NewField::ALL[next as usize];
        };
        match code {
            KeyCode::Esc => self.mode = Mode::Browse,
            KeyCode::Tab if form.focus == NewField::Dir => {
                form.dir = paths::complete(&form.dir, &form.suggestions);
                form.refresh_suggestions();
            }
            KeyCode::Down => step(form, 1),
            KeyCode::Up => step(form, -1),
            KeyCode::Enter if form.focus != NewField::Title => step(form, 1),
            KeyCode::Enter => return self.submit_new(),
            KeyCode::Char('u') if ctrl => {
                form.value_mut().clear();
                form.error = None;
                form.refresh_suggestions();
            }
            KeyCode::Backspace => {
                form.value_mut().pop();
                form.error = None;
                form.refresh_suggestions();
            }
            KeyCode::Char(c) if !ctrl => {
                form.value_mut().push(c);
                form.error = None;
                form.refresh_suggestions();
            }
            _ => {}
        }
        None
    }

    /// Checks the dialog and, if the directory exists, returns the session to start. Otherwise
    /// the dialog stays open, with the reason and the cursor in the directory field.
    fn submit_new(&mut self) -> Option<Launch> {
        let Mode::New(form) = &mut self.mode else {
            return None;
        };
        let dir = match paths::check_dir(&form.dir, home().as_deref()) {
            Ok(dir) => dir,
            Err(why) => {
                form.error = Some(why);
                form.focus = NewField::Dir;
                return None;
            }
        };
        let new = NewSession {
            dir: dir.display().to_string(),
            prompt: form.prompt.clone(),
            preset: Preset::new(tickets::parse_list(&form.tickets), Some(form.title.clone())),
        };
        let args = default_args()
            .split_whitespace()
            .map(str::to_string)
            .collect();
        self.mode = Mode::Browse;
        Some(Launch::New { new, args })
    }
}

/// An `App` with `n` titled sessions, for the tests here and in the sibling modules.
#[cfg(test)]
pub(super) fn app_with(n: usize) -> App {
    let now = chrono::Utc::now();
    let sessions = (0..n)
        .map(|i| {
            let mut s = store::new_session(&format!("id{i}"), "/x", now, now);
            s.title = Some(format!("t{i}"));
            s
        })
        .collect();
    let mut app = App {
        sessions,
        resumable: HashSet::new(),
        launch_dir: String::new(),
        query: String::new(),
        show_untitled: false,
        show_archived: false,
        only_here: false,
        only_branch: None,
        mode: Mode::Browse,
        list: ListState::default(),
        page: 10,
        status: String::new(),
    };
    app.clamp();
    app
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tag_editor_refuses_a_new_ticket_key_and_says_where_it_goes() {
        let mut app = app_with(1);
        app.apply_edit(Field::Tags, "auth ABC-123".into());
        assert!(app.status.starts_with("ABC-123 looks like a ticket key"));
        assert!(app.status.contains("^K"));
        assert!(app.sessions[0].tags.is_empty());
    }

    fn scratch_tree(name: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!("sessions-new-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        for dir in ["Code/app", "Code/api", "Code/Another Project", "Docs"] {
            std::fs::create_dir_all(root.join(dir)).unwrap();
        }
        root.canonicalize().unwrap()
    }

    fn type_text(app: &mut App, text: &str) {
        for c in text.chars() {
            assert!(app.new_key(KeyCode::Char(c), false).is_none());
        }
    }

    fn form(app: &App) -> &NewForm {
        match &app.mode {
            Mode::New(form) => form,
            _ => panic!("the new session dialog is not open"),
        }
    }

    #[test]
    fn the_dialog_starts_in_the_launch_directory_and_suggests_used_directories_first() {
        let root = scratch_tree("open");
        let mut app = app_with(2);
        app.launch_dir = root.join("Code").display().to_string();
        app.sessions[0].cwd = root.join("Docs").display().to_string();
        app.open_new();
        let f = form(&app);
        assert_eq!(f.dir, root.join("Code").display().to_string());
        assert_eq!(f.focus, NewField::Dir);
        assert!(f.error.is_none());
        // Typing after the root lists what is below it, used directories first.
        let mut app = app_with(2);
        app.launch_dir = format!("{}/", root.display());
        app.sessions[1].cwd = root.join("Docs").display().to_string();
        app.open_new();
        let found: Vec<_> = form(&app)
            .suggestions
            .iter()
            .map(|c| c.text.clone())
            .collect();
        assert_eq!(found[0], format!("{}/Docs/", root.display()), "{found:?}");
        assert!(form(&app).suggestions[0].used);
    }

    #[test]
    fn tab_completes_the_directory_and_typing_narrows_the_suggestions() {
        let root = scratch_tree("tab");
        let mut app = app_with(1);
        app.launch_dir = String::new();
        app.open_new();
        if let Mode::New(f) = &mut app.mode {
            f.dir = format!("{}/Co", root.display());
            f.refresh_suggestions();
        }
        assert!(app.new_key(KeyCode::Tab, false).is_none());
        assert_eq!(form(&app).dir, format!("{}/Code/", root.display()));
        type_text(&mut app, "An");
        assert!(app.new_key(KeyCode::Tab, false).is_none());
        assert_eq!(
            form(&app).dir,
            format!("{}/Code/Another Project/", root.display()),
            "spaces are fine"
        );
        app.new_key(KeyCode::Backspace, false);
        assert_eq!(
            form(&app).dir,
            format!("{}/Code/Another Project", root.display())
        );
    }

    #[test]
    fn enter_and_the_arrows_move_between_the_fields_and_enter_in_the_last_one_starts() {
        let root = scratch_tree("fields");
        let mut app = app_with(1);
        app.launch_dir = root.display().to_string();
        app.open_new();
        assert!(app.new_key(KeyCode::Enter, false).is_none());
        assert_eq!(form(&app).focus, NewField::Prompt);
        type_text(&mut app, "fix the login");
        app.new_key(KeyCode::Down, false);
        assert_eq!(form(&app).focus, NewField::Tickets);
        type_text(&mut app, "ABC-1, ABC-2");
        app.new_key(KeyCode::Up, false);
        app.new_key(KeyCode::Down, false);
        app.new_key(KeyCode::Enter, false);
        assert_eq!(form(&app).focus, NewField::Title);
        type_text(&mut app, "Fix login");
        // Tab outside the directory field does nothing.
        assert!(app.new_key(KeyCode::Tab, false).is_none());
        assert_eq!(form(&app).title, "Fix login");

        let Some(Launch::New { new, .. }) = app.new_key(KeyCode::Enter, false) else {
            panic!("the session was not started");
        };
        assert_eq!(new.dir, root.display().to_string());
        assert_eq!(new.prompt, "fix the login");
        assert_eq!(
            new.preset,
            Preset::new(
                vec!["ABC-1".into(), "ABC-2".into()],
                Some("Fix login".into())
            )
        );
        assert!(matches!(app.mode, Mode::Browse));
    }

    #[test]
    fn a_directory_that_does_not_exist_keeps_the_dialog_open_with_the_reason() {
        let root = scratch_tree("missing");
        let mut app = app_with(1);
        app.launch_dir = format!("{}/nope", root.display());
        app.open_new();
        for _ in 0..4 {
            assert!(app.new_key(KeyCode::Enter, false).is_none());
        }
        let f = form(&app);
        assert_eq!(
            f.error.as_deref(),
            Some(format!("No such directory: {}/nope", root.display()).as_str())
        );
        assert_eq!(
            f.focus,
            NewField::Dir,
            "the cursor goes to the field to fix"
        );
        // Typing clears the message, and a good directory then starts.
        app.new_key(KeyCode::Backspace, false);
        assert!(form(&app).error.is_none());
        if let Mode::New(f) = &mut app.mode {
            f.dir = root.join("Docs").display().to_string();
            f.focus = NewField::Title;
        }
        assert!(matches!(
            app.new_key(KeyCode::Enter, false),
            Some(Launch::New { .. })
        ));
    }

    #[test]
    fn ctrl_u_clears_the_field_with_the_cursor() {
        let root = scratch_tree("clear");
        let mut app = app_with(1);
        app.launch_dir = root.display().to_string();
        app.open_new();
        type_text(&mut app, "/more");
        assert!(app.new_key(KeyCode::Char('u'), true).is_none());
        assert_eq!(form(&app).dir, "");
        assert!(form(&app).suggestions.is_empty());
        app.new_key(KeyCode::Enter, false);
        type_text(&mut app, "message");
        app.new_key(KeyCode::Char('u'), true);
        assert_eq!(form(&app).prompt, "");
        assert_eq!(form(&app).dir, "", "only the field with the cursor");
    }

    #[test]
    fn escape_leaves_the_list_as_it_was() {
        let mut app = app_with(3);
        app.query = "t1".into();
        let before = app.visible();
        app.open_new();
        type_text(&mut app, "x");
        assert!(app.new_key(KeyCode::Esc, false).is_none());
        assert!(matches!(app.mode, Mode::Browse));
        assert_eq!(app.query, "t1");
        assert_eq!(app.visible(), before);
    }

    #[test]
    fn a_blank_title_and_no_tickets_mean_no_preset() {
        let root = scratch_tree("blank");
        let mut app = app_with(1);
        app.launch_dir = root.display().to_string();
        app.open_new();
        if let Mode::New(f) = &mut app.mode {
            f.focus = NewField::Title;
            f.title = "   ".into();
        }
        let Some(Launch::New { new, .. }) = app.new_key(KeyCode::Enter, false) else {
            panic!("not started");
        };
        assert!(new.preset.is_empty());
        assert!(new.prompt.is_empty());
    }

    fn tag_rows(app: &App) -> Vec<(String, usize)> {
        match &app.mode {
            Mode::Tags(rows, _) => rows.clone(),
            _ => panic!("the tag view is not open"),
        }
    }

    #[test]
    fn the_tag_view_counts_what_the_list_can_show() {
        let mut app = app_with(4);
        app.sessions[0].tags = vec!["auth".into(), "repair".into()];
        app.sessions[1].tags = vec!["auth".into()];
        app.sessions[2].tags = vec!["auth".into()];
        app.sessions[2].archived = true;
        app.sessions[3].tags = vec!["Repair".into()];
        app.open_tags();
        assert_eq!(
            tag_rows(&app),
            [("auth".to_string(), 2), ("repair".to_string(), 2)],
            "the archived session does not count while it is hidden"
        );
        app.show_archived = true;
        app.open_tags();
        assert_eq!(tag_rows(&app)[0], ("auth".to_string(), 3));
    }

    #[test]
    fn the_tag_view_of_sessions_without_tags_is_empty() {
        let mut app = app_with(2);
        app.open_tags();
        assert!(tag_rows(&app).is_empty());
    }

    #[test]
    fn choosing_a_tag_filters_exactly_and_choosing_it_again_clears_the_filter() {
        let mut app = app_with(3);
        app.sessions[0].tags = vec!["auth".into()];
        app.sessions[1].tags = vec!["authz".into()];
        app.toggle_tag_filter("auth");
        assert_eq!(app.query, "#auth ");
        assert_eq!(app.visible(), [0], "authz is not auth");
        app.toggle_tag_filter("auth");
        assert_eq!(app.query, "");
        assert_eq!(app.visible(), [0, 1, 2]);
    }

    #[test]
    fn archived_sessions_are_hidden_until_asked_for() {
        let mut app = app_with(3);
        app.sessions[1].archived = true;
        assert_eq!(app.visible(), [0, 2]);
        app.show_archived = true;
        assert_eq!(app.visible(), [0, 1, 2]);
        // The search still looks at archived sessions once they are shown.
        app.query = "t1".into();
        assert_eq!(app.visible(), [1]);
        app.show_archived = false;
        assert!(app.visible().is_empty());
    }

    #[test]
    fn shown_title_prefers_own_then_native_then_prompt() {
        let now = chrono::Utc::now();
        let mut s = store::new_session("a", "/x", now, now);
        assert_eq!(shown_title(&s), (TitleKind::Missing, ""));
        s.suggestion = Some("prompt".into());
        assert_eq!(shown_title(&s), (TitleKind::Suggestion, "prompt"));
        s.native_title = Some("generated".into());
        assert_eq!(shown_title(&s), (TitleKind::Native, "generated"));
        s.title = Some("mine".into());
        assert_eq!(shown_title(&s), (TitleKind::Own, "mine"));
    }

    #[test]
    fn branch_filter_keeps_only_matching_sessions() {
        let mut app = app_with(3);
        app.sessions[0].branch = Some("main".into());
        app.sessions[1].branch = Some("feat/x".into());
        app.only_branch = Some("feat/x".into());
        let ids: Vec<_> = app
            .visible()
            .iter()
            .map(|&i| app.sessions[i].id.clone())
            .collect();
        assert_eq!(ids, ["id1"]);
    }

    #[test]
    fn search_also_matches_branch_and_native_title() {
        let mut app = app_with(2);
        app.sessions[0].branch = Some("fix/oom-limit".into());
        app.sessions[1].title = None;
        app.sessions[1].native_title = Some("Grafana dashboards".into());
        app.query = "oomlimit".into();
        assert_eq!(app.visible(), [0]);
        app.query = "grafana".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn ticket_filter_is_exact_and_ignores_case_while_the_rest_stays_fuzzy() {
        let mut app = app_with(4);
        app.sessions[0].tickets = vec!["ABC-1".into()];
        app.sessions[1].tickets = vec!["ABC-12".into(), "DEF-2".into()];
        app.sessions[2].tickets = vec!["abc-1".into(), "DEF-2".into()];
        app.sessions[2].title = Some("grafana".into());

        app.query = "ticket:abc-1".into();
        assert_eq!(app.visible(), [0, 2], "ABC-12 is a different ticket");
        app.query = "ticket:ABC-1 ticket:DEF-2".into();
        assert_eq!(app.visible(), [2], "every filter has to match");
        app.query = "ticket:ABC-1 grafana".into();
        assert_eq!(app.visible(), [2], "free text narrows within the filter");
        app.query = "ticket:".into();
        assert_eq!(app.visible().len(), 4, "an unfinished filter hides nothing");
    }

    #[test]
    fn plain_search_also_finds_sessions_by_ticket_text() {
        let mut app = app_with(2);
        app.sessions[1].tickets = vec!["CLOUD-593".into()];
        app.query = "cloud593".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn paging_clamps_at_both_ends_instead_of_wrapping() {
        let mut app = app_with(25);
        app.move_by(10);
        assert_eq!(app.list.selected(), Some(10));
        app.move_by(100);
        assert_eq!(app.list.selected(), Some(24));
        app.move_by(-100);
        assert_eq!(app.list.selected(), Some(0));
        app.jump_to_end();
        assert_eq!(app.list.selected(), Some(24));
    }

    #[test]
    fn paging_an_empty_list_keeps_nothing_selected() {
        let mut app = app_with(0);
        app.move_by(10);
        app.jump_to_end();
        assert_eq!(app.list.selected(), None);
    }

    #[test]
    fn in_dir_matches_same_parent_and_child_but_not_siblings() {
        assert!(in_dir("/a/b", "/a/b"));
        assert!(in_dir("/a/b/c", "/a/b"));
        assert!(in_dir("/a/b", "/a/b/c"));
        assert!(!in_dir("/a/bc", "/a/b"));
        assert!(!in_dir("/a/x", "/a/b"));
    }
}
