//! The state of the browser and everything that changes it. `App` can be driven without a
//! terminal, which is how it is tested.

use super::Launch;
use crate::launch::default_args;
use crate::query::{self, Searcher};
use crate::store::{self, Session};
use crate::{tags, tickets, transcript};
use ratatui::widgets::ListState;
use std::collections::HashSet;
use std::process::Command;

#[derive(Clone, Copy, PartialEq)]
pub(super) enum Field {
    Title,
    Tags,
    Tickets,
    Note,
    Flags,
}

impl Field {
    pub(super) fn label(self) -> &'static str {
        match self {
            Field::Title => "Title",
            Field::Tags => "Tags (space-separated)",
            Field::Tickets => "Tickets (space or comma separated)",
            Field::Note => "Note",
            Field::Flags => "claude flags",
        }
    }
}

pub(super) enum Mode {
    Browse,
    Edit(Field, String),
    ConfirmDelete,
    /// Wrapped conversation text and the first visible line.
    Preview(Vec<String>, usize),
    /// Every tag with its number of sessions, and the selected row.
    Tags(Vec<(String, usize)>, ListState),
}

/// Where the title shown for a session comes from, in order of preference.
#[derive(Debug, PartialEq)]
pub(super) enum TitleKind {
    /// Set by the user or the agent via `sessions title`.
    Own,
    /// Generated by Claude Code itself.
    Native,
    /// First prompt of the session, cut to size.
    Suggestion,
    Missing,
}

pub(super) fn shown_title(s: &Session) -> (TitleKind, &str) {
    match (&s.title, &s.native_title, &s.suggestion) {
        (Some(t), _, _) => (TitleKind::Own, t),
        (None, Some(t), _) => (TitleKind::Native, t),
        (None, None, Some(t)) => (TitleKind::Suggestion, t),
        _ => (TitleKind::Missing, ""),
    }
}

/// Current branch of `dir`, or `None` outside a repository or on a detached HEAD.
pub(super) fn current_branch(dir: &str) -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .current_dir(dir)
        .output()
        .ok()?;
    let branch = String::from_utf8(out.stdout).ok()?.trim().to_string();
    (out.status.success() && !branch.is_empty() && branch != "HEAD").then_some(branch)
}

pub(super) struct App {
    pub(super) sessions: Vec<Session>,
    /// Ids that still have a transcript, i.e. can actually be resumed.
    pub(super) resumable: HashSet<String>,
    pub(super) launch_dir: String,
    pub(super) query: String,
    pub(super) show_untitled: bool,
    /// Whether archived sessions are listed too.
    pub(super) show_archived: bool,
    pub(super) only_here: bool,
    /// Set while filtering to the branch that is checked out in `launch_dir`.
    pub(super) only_branch: Option<String>,
    pub(super) mode: Mode,
    pub(super) list: ListState,
    /// Rows the list shows at once; set while drawing, used for PageUp/PageDown.
    pub(super) page: usize,
    pub(super) status: String,
}

pub(super) fn in_dir(session_cwd: &str, launch_dir: &str) -> bool {
    let below = |a: &str, b: &str| a == b || a.strip_prefix(b).is_some_and(|r| r.starts_with('/'));
    below(session_cwd, launch_dir) || below(launch_dir, session_cwd)
}

impl App {
    /// Indices into `sessions`, filtered and ordered for display.
    pub(super) fn visible(&self) -> Vec<usize> {
        let search = Searcher::new(&self.query);
        let mut scored: Vec<(i64, usize)> = self
            .sessions
            .iter()
            .enumerate()
            .filter(|(_, s)| self.in_scope(s))
            .filter_map(|(i, s)| search.score(s).map(|score| (score, i)))
            .collect();
        scored.sort_by(|a, b| {
            b.0.cmp(&a.0).then_with(|| {
                self.sessions[b.1]
                    .updated_at
                    .cmp(&self.sessions[a.1].updated_at)
            })
        });
        scored.into_iter().map(|(_, i)| i).collect()
    }

    /// Whether the list may show `s` before the search box is looked at: the toggles for empty and
    /// archived sessions and the directory and branch filters.
    fn in_scope(&self, s: &Session) -> bool {
        (self.show_untitled || shown_title(s).0 != TitleKind::Missing)
            && (self.show_archived || !s.archived)
            && (!self.only_here || in_dir(&s.cwd, &self.launch_dir))
            && self
                .only_branch
                .as_ref()
                .is_none_or(|b| s.branch.as_ref() == Some(b))
    }

    /// Opens the tag view. It counts the sessions the list can show, so a count matches what
    /// selecting the tag leaves in the list.
    pub(super) fn open_tags(&mut self) {
        let counts = tags::counts(self.sessions.iter().filter(|s| self.in_scope(s)));
        let mut state = ListState::default();
        state.select(if counts.is_empty() { None } else { Some(0) });
        self.mode = Mode::Tags(counts, state);
    }

    /// Adds the tag as an exact `#tag` word to the search box, or takes it out if it is there.
    pub(super) fn toggle_tag_filter(&mut self, tag: &str) {
        self.query = query::toggle_tag_word(&self.query, tag);
        self.list.select(Some(0));
        self.clamp();
    }

    /// Existing tags that could finish the word being typed in the tag editor.
    pub(super) fn tag_suggestions(&self, text: &str) -> Vec<String> {
        tags::suggestions(&tags::vocabulary(&self.sessions), text)
    }

    pub(super) fn selected(&self) -> Option<usize> {
        self.visible().get(self.list.selected()?).copied()
    }

    /// Reloads from disk and keeps the cursor on the same session even if the order changed.
    pub(super) fn reload(&mut self) {
        let selected_id = self.selected().map(|i| self.sessions[i].id.clone());
        match store::load() {
            Ok(s) => self.sessions = s,
            Err(e) => self.status = format!("{e:#}"),
        }
        self.resumable = transcript::existing_ids();
        let pos = selected_id.and_then(|id| {
            self.visible()
                .iter()
                .position(|&i| self.sessions[i].id == id)
        });
        if pos.is_some() {
            self.list.select(pos);
        }
        self.clamp();
    }

    pub(super) fn clamp(&mut self) {
        let n = self.visible().len();
        self.list.select(if n == 0 {
            None
        } else {
            Some(self.list.selected().unwrap_or(0).min(n - 1))
        });
    }

    pub(super) fn mv(&mut self, delta: isize) {
        let n = self.visible().len() as isize;
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list.select(Some((cur + delta).rem_euclid(n) as usize));
        }
    }

    /// Moves the cursor without wrapping around, for paging and the mouse wheel.
    pub(super) fn move_by(&mut self, delta: isize) {
        let n = self.visible().len();
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list
                .select(Some((cur + delta).clamp(0, n as isize - 1) as usize));
        }
    }

    pub(super) fn jump_to_end(&mut self) {
        let n = self.visible().len();
        self.list.select(n.checked_sub(1));
    }

    /// Switches the branch filter on (for the branch checked out in the launch directory) or off.
    pub(super) fn toggle_branch_filter(&mut self) {
        if self.only_branch.is_some() {
            self.only_branch = None;
        } else if let Some(branch) = current_branch(&self.launch_dir) {
            self.only_branch = Some(branch);
        } else {
            self.status = "No git branch checked out in this directory".into();
        }
        self.clamp();
    }

    pub(super) fn open_preview(&mut self, width: u16) {
        let Some(i) = self.selected() else { return };
        let Some(path) = transcript::find(&self.sessions[i].id) else {
            self.status = "Transcript is gone, nothing to preview".into();
            return;
        };
        // Leave room for the border and a column of padding.
        match transcript::preview(&path, (width as usize).saturating_sub(4)) {
            Ok(lines) if !lines.is_empty() => self.mode = Mode::Preview(lines, 0),
            Ok(_) => self.status = "Nothing to preview yet".into(),
            Err(e) => self.status = format!("{e:#}"),
        }
    }

    /// Initial text of the edit prompt for the selected session.
    pub(super) fn prefill(&self, field: Field) -> Option<String> {
        let s = &self.sessions[self.selected()?];
        Some(match field {
            Field::Title => shown_title(s).1.to_string(),
            Field::Tags => s.tags.join(" "),
            Field::Tickets => s.tickets.join(" "),
            Field::Note => s.note.clone().unwrap_or_default(),
            Field::Flags => default_args(),
        })
    }

    /// Persists an edit of the selected session. Empty titles are ignored; empty tags/notes clear them.
    pub(super) fn apply_edit(&mut self, field: Field, text: String) {
        let Some(i) = self.selected() else { return };
        if field == Field::Tags {
            let keys = crate::tags::new_ticket_keys(&self.sessions[i].tags, &text);
            if !keys.is_empty() {
                self.status = format!(
                    "{} looks like a ticket key: add it with ^K. Tags are lower case. Not saved",
                    keys.join(" ")
                );
                return;
            }
        }
        let id = self.sessions[i].id.clone();
        let res = store::update(|all| {
            let Some(s) = all.iter_mut().find(|s| s.id == id) else {
                return;
            };
            match field {
                Field::Title if !text.is_empty() => {
                    s.title = Some(text);
                    s.updated_at = chrono::Utc::now();
                }
                Field::Tags => s.tags = crate::tags::reconcile(&s.tags, &text),
                Field::Tickets => {
                    s.tickets = tickets::parse_list(&text);
                }
                Field::Note => s.note = Some(text).filter(|t| !t.is_empty()),
                _ => {}
            }
        });
        if let Err(e) = res {
            self.status = format!("{e:#}");
        }
        self.reload();
    }

    /// Archives the selected session, or brings it back if it is archived already.
    pub(super) fn toggle_archived(&mut self) {
        let Some(i) = self.selected() else { return };
        let (id, archived) = (self.sessions[i].id.clone(), !self.sessions[i].archived);
        let res = store::update(|all| {
            if let Some(s) = all.iter_mut().find(|s| s.id == id) {
                s.archived = archived;
            }
        });
        if let Err(e) = res {
            self.status = format!("{e:#}");
        }
        self.reload();
    }

    pub(super) fn launch(&mut self, i: usize, args: Vec<String>) -> Option<Launch> {
        let session = self.sessions[i].clone();
        if !self.resumable.contains(&session.id) {
            self.status =
                "Transcript is gone, so this session can't be resumed (see `sessions prune`)"
                    .into();
            return None;
        }
        Some(Launch { session, args })
    }
}

/// An `App` with `n` titled sessions, for the tests here and in the sibling modules.
#[cfg(test)]
pub(super) fn app_with(n: usize) -> App {
    let now = chrono::Utc::now();
    let sessions = (0..n)
        .map(|i| {
            let mut s = store::new_session(&format!("id{i}"), "/x", now, now);
            s.title = Some(format!("t{i}"));
            s
        })
        .collect();
    let mut app = App {
        sessions,
        resumable: HashSet::new(),
        launch_dir: String::new(),
        query: String::new(),
        show_untitled: false,
        show_archived: false,
        only_here: false,
        only_branch: None,
        mode: Mode::Browse,
        list: ListState::default(),
        page: 10,
        status: String::new(),
    };
    app.clamp();
    app
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tag_editor_refuses_a_new_ticket_key_and_says_where_it_goes() {
        let mut app = app_with(1);
        app.apply_edit(Field::Tags, "auth ABC-123".into());
        assert!(app.status.starts_with("ABC-123 looks like a ticket key"));
        assert!(app.status.contains("^K"));
        assert!(app.sessions[0].tags.is_empty());
    }

    fn tag_rows(app: &App) -> Vec<(String, usize)> {
        match &app.mode {
            Mode::Tags(rows, _) => rows.clone(),
            _ => panic!("the tag view is not open"),
        }
    }

    #[test]
    fn the_tag_view_counts_what_the_list_can_show() {
        let mut app = app_with(4);
        app.sessions[0].tags = vec!["auth".into(), "repair".into()];
        app.sessions[1].tags = vec!["auth".into()];
        app.sessions[2].tags = vec!["auth".into()];
        app.sessions[2].archived = true;
        app.sessions[3].tags = vec!["Repair".into()];
        app.open_tags();
        assert_eq!(
            tag_rows(&app),
            [("auth".to_string(), 2), ("repair".to_string(), 2)],
            "the archived session does not count while it is hidden"
        );
        app.show_archived = true;
        app.open_tags();
        assert_eq!(tag_rows(&app)[0], ("auth".to_string(), 3));
    }

    #[test]
    fn the_tag_view_of_sessions_without_tags_is_empty() {
        let mut app = app_with(2);
        app.open_tags();
        assert!(tag_rows(&app).is_empty());
    }

    #[test]
    fn choosing_a_tag_filters_exactly_and_choosing_it_again_clears_the_filter() {
        let mut app = app_with(3);
        app.sessions[0].tags = vec!["auth".into()];
        app.sessions[1].tags = vec!["authz".into()];
        app.toggle_tag_filter("auth");
        assert_eq!(app.query, "#auth ");
        assert_eq!(app.visible(), [0], "authz is not auth");
        app.toggle_tag_filter("auth");
        assert_eq!(app.query, "");
        assert_eq!(app.visible(), [0, 1, 2]);
    }

    #[test]
    fn archived_sessions_are_hidden_until_asked_for() {
        let mut app = app_with(3);
        app.sessions[1].archived = true;
        assert_eq!(app.visible(), [0, 2]);
        app.show_archived = true;
        assert_eq!(app.visible(), [0, 1, 2]);
        // The search still looks at archived sessions once they are shown.
        app.query = "t1".into();
        assert_eq!(app.visible(), [1]);
        app.show_archived = false;
        assert!(app.visible().is_empty());
    }

    #[test]
    fn shown_title_prefers_own_then_native_then_prompt() {
        let now = chrono::Utc::now();
        let mut s = store::new_session("a", "/x", now, now);
        assert_eq!(shown_title(&s), (TitleKind::Missing, ""));
        s.suggestion = Some("prompt".into());
        assert_eq!(shown_title(&s), (TitleKind::Suggestion, "prompt"));
        s.native_title = Some("generated".into());
        assert_eq!(shown_title(&s), (TitleKind::Native, "generated"));
        s.title = Some("mine".into());
        assert_eq!(shown_title(&s), (TitleKind::Own, "mine"));
    }

    #[test]
    fn branch_filter_keeps_only_matching_sessions() {
        let mut app = app_with(3);
        app.sessions[0].branch = Some("main".into());
        app.sessions[1].branch = Some("feat/x".into());
        app.only_branch = Some("feat/x".into());
        let ids: Vec<_> = app
            .visible()
            .iter()
            .map(|&i| app.sessions[i].id.clone())
            .collect();
        assert_eq!(ids, ["id1"]);
    }

    #[test]
    fn search_also_matches_branch_and_native_title() {
        let mut app = app_with(2);
        app.sessions[0].branch = Some("fix/oom-limit".into());
        app.sessions[1].title = None;
        app.sessions[1].native_title = Some("Grafana dashboards".into());
        app.query = "oomlimit".into();
        assert_eq!(app.visible(), [0]);
        app.query = "grafana".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn ticket_filter_is_exact_and_ignores_case_while_the_rest_stays_fuzzy() {
        let mut app = app_with(4);
        app.sessions[0].tickets = vec!["ABC-1".into()];
        app.sessions[1].tickets = vec!["ABC-12".into(), "DEF-2".into()];
        app.sessions[2].tickets = vec!["abc-1".into(), "DEF-2".into()];
        app.sessions[2].title = Some("grafana".into());

        app.query = "ticket:abc-1".into();
        assert_eq!(app.visible(), [0, 2], "ABC-12 is a different ticket");
        app.query = "ticket:ABC-1 ticket:DEF-2".into();
        assert_eq!(app.visible(), [2], "every filter has to match");
        app.query = "ticket:ABC-1 grafana".into();
        assert_eq!(app.visible(), [2], "free text narrows within the filter");
        app.query = "ticket:".into();
        assert_eq!(app.visible().len(), 4, "an unfinished filter hides nothing");
    }

    #[test]
    fn plain_search_also_finds_sessions_by_ticket_text() {
        let mut app = app_with(2);
        app.sessions[1].tickets = vec!["CLOUD-593".into()];
        app.query = "cloud593".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn paging_clamps_at_both_ends_instead_of_wrapping() {
        let mut app = app_with(25);
        app.move_by(10);
        assert_eq!(app.list.selected(), Some(10));
        app.move_by(100);
        assert_eq!(app.list.selected(), Some(24));
        app.move_by(-100);
        assert_eq!(app.list.selected(), Some(0));
        app.jump_to_end();
        assert_eq!(app.list.selected(), Some(24));
    }

    #[test]
    fn paging_an_empty_list_keeps_nothing_selected() {
        let mut app = app_with(0);
        app.move_by(10);
        app.jump_to_end();
        assert_eq!(app.list.selected(), None);
    }

    #[test]
    fn in_dir_matches_same_parent_and_child_but_not_siblings() {
        assert!(in_dir("/a/b", "/a/b"));
        assert!(in_dir("/a/b/c", "/a/b"));
        assert!(in_dir("/a/b", "/a/b/c"));
        assert!(!in_dir("/a/bc", "/a/b"));
        assert!(!in_dir("/a/x", "/a/b"));
    }
}
