//! Choosing sessions for the commands that report on them: the filters of `list` and `log`, and the
//! JSON view scripts read. It selects and describes sessions; it does not print or change anything.

use crate::store::Session;
use crate::{tags, tickets};
use anyhow::{Result, bail};
use chrono::{DateTime, Duration, Utc};
use serde::Serialize;
use std::path::Path;

/// What `list` keeps. An empty filter keeps everything; all given filters must match.
#[derive(Default)]
pub struct Filters {
    pub tickets: Vec<String>,
    pub tags: Vec<String>,
    pub branch: Option<String>,
    /// Sessions started in this directory or below it.
    pub cwd: Option<String>,
    /// Sessions updated at or after this time.
    pub since: Option<DateTime<Utc>>,
}

impl Filters {
    pub fn matches(&self, s: &Session) -> bool {
        tickets::has_all(s, &self.tickets)
            && tags::has_all(s, &self.tags)
            && self
                .branch
                .as_deref()
                .is_none_or(|b| s.branch.as_deref() == Some(b))
            && self
                .cwd
                .as_deref()
                .is_none_or(|dir| in_or_below(&s.cwd, dir))
            && self.since.is_none_or(|t| s.updated_at >= t)
    }
}

fn in_or_below(cwd: &str, dir: &str) -> bool {
    let dir = dir.trim_end_matches('/');
    cwd == dir
        || cwd
            .strip_prefix(dir)
            .is_some_and(|rest| rest.starts_with('/'))
}

/// An absolute form of `path` for comparing with the directories sessions were started in.
/// Relative paths are taken from the current directory; symlinks are not resolved.
pub fn absolute_dir(path: &str) -> Result<String> {
    Ok(std::path::absolute(Path::new(path))?.display().to_string())
}

/// `30m`, `12h`, `7d` or `2w`, counted back from `now`.
pub fn parse_since(text: &str, now: DateTime<Utc>) -> Result<DateTime<Utc>> {
    let text = text.trim();
    let split = text.len().saturating_sub(1);
    let (number, unit) = text.split_at(split);
    let Ok(n) = number.parse::<i64>() else {
        bail!("can't read --since {text:?}: use a number and m, h, d or w, such as 7d");
    };
    let span = match unit {
        "m" => Duration::try_minutes(n),
        "h" => Duration::try_hours(n),
        "d" => Duration::try_days(n),
        "w" => Duration::try_weeks(n),
        _ => None,
    };
    match span.and_then(|s| now.checked_sub_signed(s)) {
        Some(t) if n >= 0 => Ok(t),
        _ => bail!("can't read --since {text:?}: use a number and m, h, d or w, such as 7d"),
    }
}

/// Where the shown title comes from.
#[derive(Serialize, Debug, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum TitleSource {
    /// Set by you or the agent with `sessions title`.
    Own,
    /// Generated by Claude Code.
    Claude,
    /// The start of the first prompt.
    Prompt,
}

/// The best title there is: your own, else the one Claude Code generated, else the first prompt.
pub fn display_title(s: &Session) -> Option<(TitleSource, &str)> {
    match (&s.title, &s.native_title, &s.suggestion) {
        (Some(t), _, _) => Some((TitleSource::Own, t)),
        (None, Some(t), _) => Some((TitleSource::Claude, t)),
        (None, None, Some(t)) => Some((TitleSource::Prompt, t)),
        _ => None,
    }
}

/// The public shape of a session in `list --json`. Every key is always present, with `null` or an
/// empty list when there is no value, so scripts don't have to test for missing keys. It is
/// separate from `sessions.json` so that file's layout can change.
#[derive(Serialize, Debug)]
pub struct View<'a> {
    pub id: &'a str,
    pub title: Option<&'a str>,
    pub title_source: Option<TitleSource>,
    pub cwd: &'a str,
    pub branch: Option<&'a str>,
    pub pr_url: Option<&'a str>,
    pub tickets: &'a [String],
    pub tags: &'a [String],
    pub note: Option<&'a str>,
    pub agent: &'a str,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

pub fn view(s: &Session) -> View<'_> {
    let (title_source, title) = match display_title(s) {
        Some((source, title)) => (Some(source), Some(title)),
        None => (None, None),
    };
    View {
        id: &s.id,
        title,
        title_source,
        cwd: &s.cwd,
        branch: s.branch.as_deref(),
        pr_url: s.pr_url.as_deref(),
        tickets: &s.tickets,
        tags: &s.tags,
        note: s.note.as_deref(),
        agent: &s.agent,
        created_at: s.created_at,
        updated_at: s.updated_at,
    }
}

/// `#558` for a GitHub-style pull request URL, otherwise the URL itself.
pub fn pr_label(url: &str) -> String {
    match url.trim_end_matches('/').rsplit('/').next() {
        Some(n) if !n.is_empty() && n.chars().all(|c| c.is_ascii_digit()) => format!("#{n}"),
        _ => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::new_session;
    use chrono::TimeZone;

    fn at(day: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 10, day, 12, 0, 0).unwrap()
    }

    fn session(id: &str, cwd: &str, day: u32) -> Session {
        new_session(id, cwd, at(day), at(day))
    }

    #[test]
    fn no_filters_keep_everything() {
        assert!(Filters::default().matches(&session("a", "/x", 1)));
    }

    #[test]
    fn tags_and_tickets_match_exactly_and_all_of_them_are_required() {
        let mut s = session("a", "/x", 1);
        s.tags = vec!["observability".into(), "repair".into()];
        s.tickets = vec!["ABC-12".into()];
        let f = |tickets: &[&str], tags: &[&str]| Filters {
            tickets: tickets.iter().map(|t| t.to_string()).collect(),
            tags: tags.iter().map(|t| t.to_string()).collect(),
            ..Default::default()
        };
        assert!(f(&[], &["Observability"]).matches(&s), "case is ignored");
        assert!(f(&["abc-12"], &["repair", "observability"]).matches(&s));
        assert!(!f(&[], &["observ"]).matches(&s), "no fuzzy matching");
        assert!(!f(&["ABC-1"], &[]).matches(&s), "ABC-1 is not ABC-12");
        assert!(!f(&[], &["repair", "other"]).matches(&s));
    }

    #[test]
    fn branch_is_exact_and_cwd_includes_subdirectories_only() {
        let mut s = session("a", "/work/app/api", 1);
        s.branch = Some("feat/x".into());
        let f = |branch: Option<&str>, cwd: Option<&str>| Filters {
            branch: branch.map(String::from),
            cwd: cwd.map(String::from),
            ..Default::default()
        };
        assert!(f(Some("feat/x"), None).matches(&s));
        assert!(!f(Some("feat"), None).matches(&s));
        assert!(!f(Some("feat/x"), None).matches(&session("b", "/x", 1)));
        assert!(f(None, Some("/work/app/api")).matches(&s));
        assert!(f(None, Some("/work/app")).matches(&s));
        assert!(f(None, Some("/work/app/")).matches(&s));
        assert!(!f(None, Some("/work/ap")).matches(&s), "not a path prefix");
        assert!(!f(None, Some("/work/app/api/v2")).matches(&s));
    }

    #[test]
    fn since_keeps_sessions_updated_at_or_after_the_limit() {
        let f = Filters {
            since: Some(at(5)),
            ..Default::default()
        };
        assert!(!f.matches(&session("a", "/x", 4)));
        assert!(f.matches(&session("a", "/x", 5)));
        assert!(f.matches(&session("a", "/x", 6)));
    }

    #[test]
    fn parse_since_reads_minutes_hours_days_and_weeks() {
        let now = at(15);
        assert_eq!(
            parse_since("30m", now).unwrap(),
            now - Duration::minutes(30)
        );
        assert_eq!(parse_since("12h", now).unwrap(), now - Duration::hours(12));
        assert_eq!(parse_since("7d", now).unwrap(), at(8));
        assert_eq!(parse_since(" 2w ", now).unwrap(), at(1));
        for bad in [
            "",
            "d",
            "7",
            "7x",
            "-1d",
            "1.5d",
            "7 d",
            "99999999999999999999d",
        ] {
            assert!(parse_since(bad, now).is_err(), "{bad:?}");
        }
    }

    #[test]
    fn the_title_prefers_own_then_claude_then_prompt() {
        let mut s = session("a", "/x", 1);
        assert_eq!(display_title(&s), None);
        s.suggestion = Some("prompt".into());
        assert_eq!(display_title(&s), Some((TitleSource::Prompt, "prompt")));
        s.native_title = Some("generated".into());
        assert_eq!(display_title(&s), Some((TitleSource::Claude, "generated")));
        s.title = Some("mine".into());
        assert_eq!(display_title(&s), Some((TitleSource::Own, "mine")));
    }

    #[test]
    fn pr_label_is_the_number_for_a_pull_request_url_and_the_url_otherwise() {
        assert_eq!(pr_label("https://github.com/o/r/pull/558"), "#558");
        assert_eq!(pr_label("https://github.com/o/r/pull/558/"), "#558");
        assert_eq!(
            pr_label("https://example.test/merge/abc"),
            "https://example.test/merge/abc"
        );
    }

    #[test]
    fn the_view_always_has_every_key() {
        let json = serde_json::to_value(view(&session("a", "/x", 1))).unwrap();
        let keys: Vec<_> = json.as_object().unwrap().keys().cloned().collect();
        assert_eq!(
            keys,
            [
                "id",
                "title",
                "title_source",
                "cwd",
                "branch",
                "pr_url",
                "tickets",
                "tags",
                "note",
                "agent",
                "created_at",
                "updated_at"
            ]
        );
        assert!(json["title"].is_null() && json["branch"].is_null());
        assert_eq!(json["tags"], serde_json::json!([]));
        assert_eq!(json["agent"], "claude-code");
    }
}
