//! The ratatui browser. `App` holds all state and handles input without a terminal, so it can be
//! unit-tested; drawing and the `exec` into `claude --resume` stay at the edge.

use crate::store::{self, Session};
use crate::{tickets, transcript};
use anyhow::Result;
use fuzzy_matcher::{FuzzyMatcher, skim::SkimMatcherV2};
use ratatui::{
    DefaultTerminal, Frame,
    crossterm::event::{
        self, DisableMouseCapture, EnableMouseCapture, Event, KeyCode, KeyEventKind, KeyModifiers,
        MouseEventKind,
    },
    layout::{Constraint, Layout},
    style::{Modifier, Style, Stylize},
    text::{Line, Span},
    widgets::{
        Block, Borders, Clear, List, ListItem, ListState, Paragraph, Scrollbar,
        ScrollbarOrientation, ScrollbarState,
    },
};
use std::collections::HashSet;
use std::os::unix::process::CommandExt;
use std::path::Path;
use std::process::Command;

#[derive(Clone, Copy, PartialEq)]
enum Field {
    Title,
    Tags,
    Tickets,
    Note,
    Flags,
}

impl Field {
    fn label(self) -> &'static str {
        match self {
            Field::Title => "Title",
            Field::Tags => "Tags (space-separated)",
            Field::Tickets => "Tickets (space or comma separated)",
            Field::Note => "Note",
            Field::Flags => "claude flags",
        }
    }
}

enum Mode {
    Browse,
    Edit(Field, String),
    ConfirmDelete,
    /// Wrapped conversation text and the first visible line.
    Preview(Vec<String>, usize),
}

/// Where the title shown for a session comes from, in order of preference.
#[derive(Debug, PartialEq)]
enum TitleKind {
    /// Set by the user or the agent via `sessions title`.
    Own,
    /// Generated by Claude Code itself.
    Native,
    /// First prompt of the session, cut to size.
    Suggestion,
    Missing,
}

fn shown_title(s: &Session) -> (TitleKind, &str) {
    match (&s.title, &s.native_title, &s.suggestion) {
        (Some(t), _, _) => (TitleKind::Own, t),
        (None, Some(t), _) => (TitleKind::Native, t),
        (None, None, Some(t)) => (TitleKind::Suggestion, t),
        _ => (TitleKind::Missing, ""),
    }
}

/// `1.5 MB`, `300 KB`, `12 B`.
fn human_size(bytes: u64) -> String {
    const UNITS: [&str; 4] = ["B", "KB", "MB", "GB"];
    let (mut value, mut unit) = (bytes as f64, 0);
    while value >= 1024.0 && unit < UNITS.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{bytes} B")
    } else {
        format!("{value:.1} {}", UNITS[unit])
    }
}

/// Current branch of `dir`, or `None` outside a repository or on a detached HEAD.
fn current_branch(dir: &str) -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .current_dir(dir)
        .output()
        .ok()?;
    let branch = String::from_utf8(out.stdout).ok()?.trim().to_string();
    (out.status.success() && !branch.is_empty() && branch != "HEAD").then_some(branch)
}

struct App {
    sessions: Vec<Session>,
    /// Ids that still have a transcript, i.e. can actually be resumed.
    resumable: HashSet<String>,
    launch_dir: String,
    query: String,
    show_untitled: bool,
    only_here: bool,
    /// Set while filtering to the branch that is checked out in `launch_dir`.
    only_branch: Option<String>,
    mode: Mode,
    list: ListState,
    /// Rows the list shows at once; set while drawing, used for PageUp/PageDown.
    page: usize,
    status: String,
}

/// Below this terminal height the details pane is dropped to leave room for the list.
const MIN_HEIGHT_FOR_DETAILS: u16 = 25;
/// Border plus seven lines of details.
const DETAILS_HEIGHT: u16 = 9;
/// Rows scrolled per mouse wheel notch.
const WHEEL_STEP: isize = 3;

/// What to run after the TUI has closed.
struct Launch {
    session: Session,
    args: Vec<String>,
}

fn default_args() -> String {
    std::env::var("SESSIONS_CLAUDE_ARGS").unwrap_or_default()
}

fn in_dir(session_cwd: &str, launch_dir: &str) -> bool {
    let below = |a: &str, b: &str| a == b || a.strip_prefix(b).is_some_and(|r| r.starts_with('/'));
    below(session_cwd, launch_dir) || below(launch_dir, session_cwd)
}

impl App {
    /// Indices into `sessions`, filtered and ordered for display.
    fn visible(&self) -> Vec<usize> {
        let matcher = SkimMatcherV2::default();
        let (free_text, ticket_filters) = tickets::parse_query(&self.query);
        let mut scored: Vec<(i64, usize)> = self
            .sessions
            .iter()
            .enumerate()
            .filter(|(_, s)| self.show_untitled || shown_title(s).0 != TitleKind::Missing)
            .filter(|(_, s)| !self.only_here || in_dir(&s.cwd, &self.launch_dir))
            .filter(|(_, s)| {
                self.only_branch
                    .as_ref()
                    .is_none_or(|b| s.branch.as_ref() == Some(b))
            })
            .filter(|(_, s)| tickets::has_all(s, &ticket_filters))
            .filter_map(|(i, s)| {
                if free_text.is_empty() {
                    return Some((0, i));
                }
                let hay = format!(
                    "{} {} {} {} {} {} {}",
                    shown_title(s).1,
                    s.cwd,
                    s.tickets.join(" "),
                    s.tags.join(" "),
                    s.note.as_deref().unwrap_or(""),
                    s.branch.as_deref().unwrap_or(""),
                    s.pr_url.as_deref().unwrap_or("")
                );
                matcher
                    .fuzzy_match(&hay, &free_text)
                    .map(|score| (score, i))
            })
            .collect();
        scored.sort_by(|a, b| {
            b.0.cmp(&a.0).then_with(|| {
                self.sessions[b.1]
                    .updated_at
                    .cmp(&self.sessions[a.1].updated_at)
            })
        });
        scored.into_iter().map(|(_, i)| i).collect()
    }

    fn selected(&self) -> Option<usize> {
        self.visible().get(self.list.selected()?).copied()
    }

    /// Reloads from disk and keeps the cursor on the same session even if the order changed.
    fn reload(&mut self) {
        let selected_id = self.selected().map(|i| self.sessions[i].id.clone());
        match store::load() {
            Ok(s) => self.sessions = s,
            Err(e) => self.status = format!("{e:#}"),
        }
        self.resumable = transcript::existing_ids();
        let pos = selected_id.and_then(|id| {
            self.visible()
                .iter()
                .position(|&i| self.sessions[i].id == id)
        });
        if pos.is_some() {
            self.list.select(pos);
        }
        self.clamp();
    }

    fn clamp(&mut self) {
        let n = self.visible().len();
        self.list.select(if n == 0 {
            None
        } else {
            Some(self.list.selected().unwrap_or(0).min(n - 1))
        });
    }

    fn mv(&mut self, delta: isize) {
        let n = self.visible().len() as isize;
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list.select(Some((cur + delta).rem_euclid(n) as usize));
        }
    }

    /// Moves the cursor without wrapping around, for paging and the mouse wheel.
    fn move_by(&mut self, delta: isize) {
        let n = self.visible().len();
        if n > 0 {
            let cur = self.list.selected().unwrap_or(0) as isize;
            self.list
                .select(Some((cur + delta).clamp(0, n as isize - 1) as usize));
        }
    }

    fn jump_to_end(&mut self) {
        let n = self.visible().len();
        self.list.select(n.checked_sub(1));
    }

    /// Switches the branch filter on (for the branch checked out in the launch directory) or off.
    fn toggle_branch_filter(&mut self) {
        if self.only_branch.is_some() {
            self.only_branch = None;
        } else if let Some(branch) = current_branch(&self.launch_dir) {
            self.only_branch = Some(branch);
        } else {
            self.status = "No git branch checked out in this directory".into();
        }
        self.clamp();
    }

    fn open_preview(&mut self, width: u16) {
        let Some(i) = self.selected() else { return };
        let Some(path) = transcript::find(&self.sessions[i].id) else {
            self.status = "Transcript is gone, nothing to preview".into();
            return;
        };
        // Leave room for the border and a column of padding.
        match transcript::preview(&path, (width as usize).saturating_sub(4)) {
            Ok(lines) if !lines.is_empty() => self.mode = Mode::Preview(lines, 0),
            Ok(_) => self.status = "Nothing to preview yet".into(),
            Err(e) => self.status = format!("{e:#}"),
        }
    }

    /// Initial text of the edit prompt for the selected session.
    fn prefill(&self, field: Field) -> Option<String> {
        let s = &self.sessions[self.selected()?];
        Some(match field {
            Field::Title => shown_title(s).1.to_string(),
            Field::Tags => s.tags.join(" "),
            Field::Tickets => s.tickets.join(" "),
            Field::Note => s.note.clone().unwrap_or_default(),
            Field::Flags => default_args(),
        })
    }

    /// Persists an edit of the selected session. Empty titles are ignored; empty tags/notes clear them.
    fn apply_edit(&mut self, field: Field, text: String) {
        let Some(i) = self.selected() else { return };
        if field == Field::Tags {
            let keys = crate::tags::new_ticket_keys(&self.sessions[i].tags, &text);
            if !keys.is_empty() {
                self.status = format!(
                    "{} looks like a ticket key: add it with ^K. Tags are lower case. Not saved",
                    keys.join(" ")
                );
                return;
            }
        }
        let id = self.sessions[i].id.clone();
        let res = store::update(|all| {
            let Some(s) = all.iter_mut().find(|s| s.id == id) else {
                return;
            };
            match field {
                Field::Title if !text.is_empty() => {
                    s.title = Some(text);
                    s.updated_at = chrono::Utc::now();
                }
                Field::Tags => s.tags = crate::tags::reconcile(&s.tags, &text),
                Field::Tickets => {
                    s.tickets = tickets::parse_list(&text);
                }
                Field::Note => s.note = Some(text).filter(|t| !t.is_empty()),
                _ => {}
            }
        });
        if let Err(e) = res {
            self.status = format!("{e:#}");
        }
        self.reload();
    }

    fn launch(&mut self, i: usize, args: Vec<String>) -> Option<Launch> {
        let session = self.sessions[i].clone();
        if !self.resumable.contains(&session.id) {
            self.status =
                "Transcript is gone, so this session can't be resumed (see `sessions prune`)"
                    .into();
            return None;
        }
        Some(Launch { session, args })
    }
}

pub fn run() -> Result<()> {
    // Pull in what Claude Code recorded itself (generated title, branch, PR), give untitled
    // sessions a fallback title from their first prompt, and sort by real activity (transcript
    // mtime) rather than just session starts.
    store::update(|all| {
        transcript::refresh_meta(all);
        for s in all.iter_mut() {
            transcript::fill_suggestion(s);
        }
        transcript::sync_activity(all);
    })?;

    let mut app = App {
        sessions: Vec::new(),
        resumable: HashSet::new(),
        launch_dir: std::env::current_dir()
            .map(|p| p.display().to_string())
            .unwrap_or_default(),
        query: String::new(),
        show_untitled: false,
        only_here: false,
        only_branch: None,
        mode: Mode::Browse,
        list: ListState::default(),
        page: 10,
        status: String::new(),
    };
    app.sessions = store::load()?;
    app.resumable = transcript::existing_ids();
    app.clamp();

    let mut terminal = ratatui::init();
    // Without mouse capture the wheel only scrolls if the terminal maps it to arrow keys.
    // Capturing it makes plain text selection need Shift (Option in some terminals).
    let _ = ratatui::crossterm::execute!(std::io::stdout(), EnableMouseCapture);
    let result = event_loop(&mut terminal, &mut app);
    let _ = ratatui::crossterm::execute!(std::io::stdout(), DisableMouseCapture);
    ratatui::restore();

    if let Some(Launch { session, args }) = result? {
        // Replaces this process; only returns on failure.
        let err = Command::new("claude")
            .arg("--resume")
            .arg(&session.id)
            .args(&args)
            .current_dir(&session.cwd)
            .exec();
        anyhow::bail!("could not start claude in {}: {err}", session.cwd);
    }
    Ok(())
}

/// Moves a scroll offset by `delta`. The last page stays full instead of scrolling the final
/// line to the top.
fn scroll_by(cur: usize, delta: isize, len: usize, page: usize) -> usize {
    (cur as isize + delta).clamp(0, len.saturating_sub(page) as isize) as usize
}

fn event_loop(terminal: &mut DefaultTerminal, app: &mut App) -> Result<Option<Launch>> {
    loop {
        terminal.draw(|f| draw(f, app))?;
        let key = match event::read()? {
            Event::Key(key) => key,
            Event::Mouse(m) => {
                let delta = match m.kind {
                    MouseEventKind::ScrollUp => -WHEEL_STEP,
                    MouseEventKind::ScrollDown => WHEEL_STEP,
                    _ => 0,
                };
                match &mut app.mode {
                    Mode::Browse => app.move_by(delta),
                    Mode::Preview(lines, scroll) => {
                        *scroll = scroll_by(*scroll, delta, lines.len(), app.page)
                    }
                    _ => {}
                }
                continue;
            }
            _ => continue,
        };
        if key.kind != KeyEventKind::Press {
            continue;
        }
        let ctrl = key.modifiers.contains(KeyModifiers::CONTROL);
        app.status.clear();

        match &mut app.mode {
            Mode::Preview(lines, scroll) => {
                let (len, page) = (lines.len(), app.page);
                let by = |cur: usize, delta: isize| scroll_by(cur, delta, len, page);
                match key.code {
                    KeyCode::Esc | KeyCode::Char('q') => app.mode = Mode::Browse,
                    KeyCode::Char('v') if ctrl => app.mode = Mode::Browse,
                    KeyCode::Up => *scroll = by(*scroll, -1),
                    KeyCode::Down => *scroll = by(*scroll, 1),
                    KeyCode::PageUp => *scroll = by(*scroll, -(page as isize)),
                    KeyCode::PageDown => *scroll = by(*scroll, page as isize),
                    KeyCode::Home => *scroll = 0,
                    KeyCode::End => *scroll = len.saturating_sub(page),
                    _ => {}
                }
            }
            Mode::Edit(field, buf) => match key.code {
                KeyCode::Esc => app.mode = Mode::Browse,
                KeyCode::Enter => {
                    let (field, text) = (*field, buf.trim().to_string());
                    app.mode = Mode::Browse;
                    if let Field::Flags = field {
                        if let Some(i) = app.selected() {
                            let args = text.split_whitespace().map(str::to_string).collect();
                            if let Some(l) = app.launch(i, args) {
                                return Ok(Some(l));
                            }
                        }
                    } else {
                        app.apply_edit(field, text);
                    }
                }
                KeyCode::Backspace => {
                    buf.pop();
                }
                KeyCode::Char(c) if !ctrl => buf.push(c),
                _ => {}
            },
            Mode::ConfirmDelete => {
                if matches!(key.code, KeyCode::Char('y'))
                    && let Some(i) = app.selected()
                {
                    let id = app.sessions[i].id.clone();
                    if let Err(e) = store::update(|all| all.retain(|s| s.id != id)) {
                        app.status = format!("{e:#}");
                    }
                    app.reload();
                }
                app.mode = Mode::Browse;
            }
            Mode::Browse => match key.code {
                KeyCode::Esc => return Ok(None),
                KeyCode::Char('c') if ctrl => return Ok(None),
                KeyCode::Enter => {
                    if let Some(i) = app.selected() {
                        let args = default_args()
                            .split_whitespace()
                            .map(str::to_string)
                            .collect();
                        if let Some(l) = app.launch(i, args) {
                            return Ok(Some(l));
                        }
                    }
                }
                KeyCode::Up => app.mv(-1),
                KeyCode::Down => app.mv(1),
                KeyCode::PageUp => app.move_by(-(app.page as isize)),
                KeyCode::PageDown => app.move_by(app.page as isize),
                KeyCode::Home => app.list.select(Some(0)),
                KeyCode::End => app.jump_to_end(),
                KeyCode::Char('p') if ctrl => app.mv(-1),
                KeyCode::Char('n') if ctrl => app.mv(1),
                KeyCode::Tab => {
                    app.show_untitled = !app.show_untitled;
                    app.clamp();
                }
                KeyCode::Char('l') if ctrl => {
                    app.only_here = !app.only_here;
                    app.clamp();
                }
                KeyCode::Char('b') if ctrl => app.toggle_branch_filter(),
                KeyCode::Char('v') if ctrl => app.open_preview(terminal.size()?.width),
                KeyCode::Char(c @ ('r' | 't' | 'k' | 'e' | 'o')) if ctrl => {
                    let field = match c {
                        'r' => Field::Title,
                        't' => Field::Tags,
                        'k' => Field::Tickets,
                        'e' => Field::Note,
                        _ => Field::Flags,
                    };
                    if let Some(text) = app.prefill(field) {
                        app.mode = Mode::Edit(field, text);
                    }
                }
                KeyCode::Char('x') if ctrl => {
                    if app.selected().is_some() {
                        app.mode = Mode::ConfirmDelete;
                    }
                }
                KeyCode::Backspace => {
                    app.query.pop();
                    app.clamp();
                }
                KeyCode::Char(c) if !ctrl => {
                    app.query.push(c);
                    app.list.select(Some(0));
                    app.clamp();
                }
                _ => {}
            },
        }
    }
}

fn draw(f: &mut Frame, app: &mut App) {
    let detail_height = if f.area().height >= MIN_HEIGHT_FOR_DETAILS {
        DETAILS_HEIGHT
    } else {
        0
    };
    let [search, body, detail, help] = Layout::vertical([
        Constraint::Length(3),
        Constraint::Min(3),
        Constraint::Length(detail_height),
        Constraint::Length(1),
    ])
    .areas(f.area());
    // Inner height of the bordered list.
    app.page = body.height.saturating_sub(2).max(1) as usize;

    let hidden = app
        .sessions
        .iter()
        .filter(|s| shown_title(s).0 == TitleKind::Missing)
        .count();
    let mut search_title = if app.show_untitled {
        " Sessions (all)".to_string()
    } else {
        format!(" Sessions ({hidden} empty hidden)")
    };
    if app.only_here {
        search_title += " · this directory only";
    }
    if let Some(branch) = &app.only_branch {
        search_title += &format!(" · branch {branch}");
    }
    let wanted = tickets::parse_query(&app.query).1;
    if !wanted.is_empty() {
        search_title += &format!(" · ticket {}", wanted.join(", "));
    }
    search_title.push(' ');
    f.render_widget(
        Paragraph::new(format!("> {}", app.query))
            .block(Block::default().borders(Borders::ALL).title(search_title)),
        search,
    );

    let visible = app.visible();
    let items: Vec<ListItem> = visible
        .iter()
        .map(|&i| {
            let s = &app.sessions[i];
            let mut spans = Vec::new();
            if !app.resumable.contains(&s.id) {
                spans.push(Span::raw("✗ ").red());
            }
            spans.push(
                Span::raw(
                    s.updated_at
                        .with_timezone(&chrono::Local)
                        .format("%Y-%m-%d %H:%M  ")
                        .to_string(),
                )
                .dim(),
            );
            let dir = Path::new(&s.cwd)
                .file_name()
                .map(|d| d.to_string_lossy().into_owned())
                .unwrap_or_default();
            spans.push(Span::raw(format!("{:<18.18}  ", dir)).cyan());
            let (kind, title) = shown_title(s);
            spans.push(match kind {
                TitleKind::Own => Span::raw(title.to_string()),
                TitleKind::Native => Span::raw(title.to_string()).italic(),
                TitleKind::Suggestion => Span::raw(format!("~ {title}")).dim().italic(),
                TitleKind::Missing => Span::raw("(untitled)").dim().italic(),
            });
            if !s.tickets.is_empty() {
                spans.push(Span::raw(format!("  [{}]", s.tickets.join(" "))).magenta());
            }
            if !s.tags.is_empty() {
                spans.push(Span::raw(format!("  #{}", s.tags.join(" #"))).yellow());
            }
            if let Some(branch) = &s.branch {
                spans.push(Span::raw(format!("  ⎇ {branch}")).dim());
            }
            Line::from(spans).into()
        })
        .collect();
    let list = List::new(items)
        .block(Block::default().borders(Borders::ALL))
        .highlight_style(Style::default().add_modifier(Modifier::REVERSED))
        .highlight_symbol("▶ ");
    f.render_stateful_widget(list, body, &mut app.list);
    if visible.len() > app.page {
        let mut scrollbar = ScrollbarState::new(visible.len())
            .viewport_content_length(app.page)
            .position(app.list.selected().unwrap_or(0));
        f.render_stateful_widget(
            Scrollbar::new(ScrollbarOrientation::VerticalRight),
            body,
            &mut scrollbar,
        );
    }

    let detail_text = match app.selected().map(|i| &app.sessions[i]) {
        Some(s) => {
            let git = match (&s.branch, &s.pr_url) {
                (None, None) => "-".to_string(),
                (b, pr) => [
                    b.clone(),
                    pr.as_deref().map(|u| format!("PR {} ({u})", pr_label(u))),
                ]
                .into_iter()
                .flatten()
                .collect::<Vec<_>>()
                .join("  ·  "),
            };
            let size = transcript::find(&s.id)
                .and_then(|p| std::fs::metadata(p).ok())
                .map_or("transcript gone".to_string(), |m| human_size(m.len()));
            let title_from = match shown_title(s).0 {
                TitleKind::Own => "title set by you or the agent",
                TitleKind::Native => "title generated by Claude Code",
                TitleKind::Suggestion => "title cut from the first prompt",
                TitleKind::Missing => "no title",
            };
            format!(
                "cwd:     {}\nid:      {}\ngit:     {git}\ntickets: {}\ntags:    {}\nnote:    {}\nfile:    {size}  ·  {title_from}",
                s.cwd,
                s.id,
                if s.tickets.is_empty() {
                    "-".to_string()
                } else {
                    s.tickets.join(" ")
                },
                if s.tags.is_empty() {
                    "-".to_string()
                } else {
                    s.tags.join(" ")
                },
                s.note.as_deref().unwrap_or("-")
            )
        }
        None => "No session selected".to_string(),
    };
    if detail_height > 0 {
        f.render_widget(
            Paragraph::new(detail_text)
                .block(Block::default().borders(Borders::ALL).title(" Details ")),
            detail,
        );
    }

    let help_line = match &app.mode {
        Mode::Edit(field, buf) => Line::from(format!("{}: {buf}█   (Enter to confirm, Esc to cancel)", field.label())),
        Mode::ConfirmDelete => Line::from("Really delete this session? (y = yes, anything else cancels)".red()),
        Mode::Preview(..) => Line::from("".dim()),
        Mode::Browse if !app.status.is_empty() => Line::from(app.status.clone().red()),
        Mode::Browse => Line::from(
            "Enter resume  ^V preview  ^O flags  Tab empty  ^L dir  ^B branch  ^R title  ^T tags  ^K tickets  ^E note  ^X delete  Esc quit".dim(),
        ),
    };
    f.render_widget(Paragraph::new(help_line), help);

    // The preview covers everything, so it is drawn last. It pages by its own height.
    let preview_page = f.area().height.saturating_sub(2).max(1) as usize;
    let mut previewing = false;
    if let Mode::Preview(lines, scroll) = &app.mode {
        previewing = true;
        let area = f.area();
        let end = (*scroll + preview_page).min(lines.len());
        let text: Vec<Line> = lines[*scroll..end]
            .iter()
            .map(|l| match l.as_str() {
                "── you ──" => Line::from(l.as_str()).yellow().bold(),
                "── claude ──" => Line::from(l.as_str()).green().bold(),
                _ => Line::from(l.as_str()),
            })
            .collect();
        f.render_widget(Clear, area);
        f.render_widget(
            Paragraph::new(text).block(Block::default().borders(Borders::ALL).title(format!(
                " Preview · {}/{} · ↑↓ PgUp PgDn Home End scroll · Esc closes ",
                (*scroll + 1).min(lines.len()),
                lines.len()
            ))),
            area,
        );
        if lines.len() > preview_page {
            let mut bar = ScrollbarState::new(lines.len())
                .viewport_content_length(preview_page)
                .position(*scroll);
            f.render_stateful_widget(
                Scrollbar::new(ScrollbarOrientation::VerticalRight),
                area,
                &mut bar,
            );
        }
    }
    if previewing {
        app.page = preview_page;
    }
}

/// `#558` for a GitHub-style pull request URL, otherwise the URL itself.
fn pr_label(url: &str) -> String {
    match url.trim_end_matches('/').rsplit('/').next() {
        Some(n) if !n.is_empty() && n.chars().all(|c| c.is_ascii_digit()) => format!("#{n}"),
        _ => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app_with(n: usize) -> App {
        let now = chrono::Utc::now();
        let sessions = (0..n)
            .map(|i| {
                let mut s = store::new_session(&format!("id{i}"), "/x", now, now);
                s.title = Some(format!("t{i}"));
                s
            })
            .collect();
        let mut app = App {
            sessions,
            resumable: HashSet::new(),
            launch_dir: String::new(),
            query: String::new(),
            show_untitled: false,
            only_here: false,
            only_branch: None,
            mode: Mode::Browse,
            list: ListState::default(),
            page: 10,
            status: String::new(),
        };
        app.clamp();
        app
    }

    #[test]
    fn tag_editor_refuses_a_new_ticket_key_and_says_where_it_goes() {
        let mut app = app_with(1);
        app.apply_edit(Field::Tags, "auth ABC-123".into());
        assert!(app.status.starts_with("ABC-123 looks like a ticket key"));
        assert!(app.status.contains("^K"));
        assert!(app.sessions[0].tags.is_empty());
    }

    #[test]
    fn shown_title_prefers_own_then_native_then_prompt() {
        let now = chrono::Utc::now();
        let mut s = store::new_session("a", "/x", now, now);
        assert_eq!(shown_title(&s), (TitleKind::Missing, ""));
        s.suggestion = Some("prompt".into());
        assert_eq!(shown_title(&s), (TitleKind::Suggestion, "prompt"));
        s.native_title = Some("generated".into());
        assert_eq!(shown_title(&s), (TitleKind::Native, "generated"));
        s.title = Some("mine".into());
        assert_eq!(shown_title(&s), (TitleKind::Own, "mine"));
    }

    #[test]
    fn branch_filter_keeps_only_matching_sessions() {
        let mut app = app_with(3);
        app.sessions[0].branch = Some("main".into());
        app.sessions[1].branch = Some("feat/x".into());
        app.only_branch = Some("feat/x".into());
        let ids: Vec<_> = app
            .visible()
            .iter()
            .map(|&i| app.sessions[i].id.clone())
            .collect();
        assert_eq!(ids, ["id1"]);
    }

    #[test]
    fn search_also_matches_branch_and_native_title() {
        let mut app = app_with(2);
        app.sessions[0].branch = Some("fix/oom-limit".into());
        app.sessions[1].title = None;
        app.sessions[1].native_title = Some("Grafana dashboards".into());
        app.query = "oomlimit".into();
        assert_eq!(app.visible(), [0]);
        app.query = "grafana".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn ticket_filter_is_exact_and_ignores_case_while_the_rest_stays_fuzzy() {
        let mut app = app_with(4);
        app.sessions[0].tickets = vec!["ABC-1".into()];
        app.sessions[1].tickets = vec!["ABC-12".into(), "DEF-2".into()];
        app.sessions[2].tickets = vec!["abc-1".into(), "DEF-2".into()];
        app.sessions[2].title = Some("grafana".into());

        app.query = "ticket:abc-1".into();
        assert_eq!(app.visible(), [0, 2], "ABC-12 is a different ticket");
        app.query = "ticket:ABC-1 ticket:DEF-2".into();
        assert_eq!(app.visible(), [2], "every filter has to match");
        app.query = "ticket:ABC-1 grafana".into();
        assert_eq!(app.visible(), [2], "free text narrows within the filter");
        app.query = "ticket:".into();
        assert_eq!(app.visible().len(), 4, "an unfinished filter hides nothing");
    }

    #[test]
    fn plain_search_also_finds_sessions_by_ticket_text() {
        let mut app = app_with(2);
        app.sessions[1].tickets = vec!["CLOUD-593".into()];
        app.query = "cloud593".into();
        assert_eq!(app.visible(), [1]);
    }

    #[test]
    fn human_size_and_pr_label_and_scroll_by() {
        assert_eq!(human_size(12), "12 B");
        assert_eq!(human_size(1536), "1.5 KB");
        assert_eq!(human_size(5 * 1024 * 1024), "5.0 MB");
        assert_eq!(pr_label("https://github.com/o/r/pull/558"), "#558");
        assert_eq!(
            pr_label("https://example.test/merge/abc"),
            "https://example.test/merge/abc"
        );
        assert_eq!(scroll_by(5, 100, 20, 8), 12);
        assert_eq!(scroll_by(5, -100, 20, 8), 0);
        assert_eq!(scroll_by(0, 3, 0, 8), 0);
        assert_eq!(scroll_by(0, 3, 5, 8), 0);
    }

    #[test]
    fn paging_clamps_at_both_ends_instead_of_wrapping() {
        let mut app = app_with(25);
        app.move_by(10);
        assert_eq!(app.list.selected(), Some(10));
        app.move_by(100);
        assert_eq!(app.list.selected(), Some(24));
        app.move_by(-100);
        assert_eq!(app.list.selected(), Some(0));
        app.jump_to_end();
        assert_eq!(app.list.selected(), Some(24));
    }

    #[test]
    fn paging_an_empty_list_keeps_nothing_selected() {
        let mut app = app_with(0);
        app.move_by(10);
        app.jump_to_end();
        assert_eq!(app.list.selected(), None);
    }

    #[test]
    fn in_dir_matches_same_parent_and_child_but_not_siblings() {
        assert!(in_dir("/a/b", "/a/b"));
        assert!(in_dir("/a/b/c", "/a/b"));
        assert!(in_dir("/a/b", "/a/b/c"));
        assert!(!in_dir("/a/bc", "/a/b"));
        assert!(!in_dir("/a/x", "/a/b"));
    }
}
